In [1]:
import pandas as pd
from sklearn.svm import LinearSVC
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
#Load Dataset
df = pd.read_csv("dataset.csv")
df.head(50)

,Stars,Title_of_Review,Base_Review,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,1.0 out of 5 stars,This is a ripoff. And shame on Amazon for not ...,Don't buy this product. I purchased it for my ...,NaN,NaN,NaN
1,1.0 out of 5 stars,PDF Max Pro doesn't play well with marshmallow,"Get an ""invalid file"" error since Marshmallow.",NaN,NaN,NaN
2,1.0 out of 5 stars,Worse app ever,I wouldn't even give it a one if I could. I wi...,NaN,NaN,NaN
3,1.0 out of 5 stars,I'd recommend trying to email the developer fi...,"If I could give it less stars, I would! Does n...",NaN,NaN,NaN
4,5.0 out of 5 stars,Amazing For Markup,I have several apps that can open pdf files on...,NaN,NaN,NaN
5,2.0 out of 5 stars,Tools work great but loses files,The app works great for reading and annotating...,NaN,NaN,NaN
6,1.0 out of 5 stars,Doesn't Work At All,"Wow... PDF Files are ""invalid"" and cannot be ...",NaN,NaN,NaN
7,3.0 out of 5 stars,"Alright, but EZ PDF is better. (One Reason Only)",This app is good at its job. There is still on...,NaN,NaN,NaN
8,3.0 out of 5 stars,College Student review,Has a lot of good features. I'm not going to g...,NaN,NaN,NaN
9,3.0 out of 5 stars,Nice app except for one BIG thing,This would be a fantastic app except for one b...,NaN,NaN,NaN
10,1.0 out of 5 stars,I got a new tablet with Marshmallow. Apparentl...,I got a new tablet with Marshmallow. Apparent...,NaN,NaN,NaN
11,3.0 out of 5 stars,Almost there.,Seeing as how this app is as expensive as many...,NaN,NaN,NaN
12,1.0 out of 5 stars,"Do you update to 4.6.4, it's broken!","It used to be good, but the latest update 4.6....",NaN,NaN,NaN
13,1.0 out of 5 stars,Terrible terrible,I tried my best to give a benefit of a doubt. ...,NaN,NaN,NaN
14,1.0 out of 5 stars,Crashes the system - will not start,This program listed it would work on my kindle...,NaN,NaN,NaN
15,5.0 out of 5 stars,Great for Studying!,"This is so awesome! I used to use Adobe, but ...",NaN,NaN,NaN
16,2.0 out of 5 stars,Almost works,"Fine on small files, hangs on large.Won't load...",NaN,NaN,NaN
17,1.0 out of 5 stars,Crashes and invalid,App doesn't work. It hasn't for the longest ti...,NaN,NaN,NaN
18,4.0 out of 5 stars,pretty much everything I was looking for,I was looking for an app to be able to annotat...,NaN,NaN,NaN
19,1.0 out of 5 stars,Invalid file,"After upgrading to Android 6 (apparently), PDF...",NaN,NaN,NaN
20,4.0 out of 5 stars,A high quality PDF reader that works fairly well!,Update 6-17-2015I rescanned this software afte...,NaN,NaN,NaN
21,5.0 out of 5 stars,The best pdf viewer I have seen,For the desktop I've always been a big fan of ...,NaN,NaN,NaN
22,4.0 out of 5 stars,"Great app for my purposes...plus, NO ADS!!!",I just purchased this app for reading and anno...,NaN,NaN,NaN
23,1.0 out of 5 stars,"New permissions are a drag, and internet the r...",The new permissions really sour what is an oth...,NaN,NaN,NaN
24,1.0 out of 5 stars,Total Piece of Crap that Doesn't Even Work - I...,I gave Amazon $4.00 for it and it crashes ever...,NaN,NaN,NaN
25,4.0 out of 5 stars,Won't open....... Problem fixed,"Downloaded app and won't work, says interactiv...",NaN,NaN,NaN
26,1.0 out of 5 stars,Warning!!! Will not open on Kindle Fire,Continuously crashes. Cannot open even after r...,NaN,NaN,NaN
27,4.0 out of 5 stars,Must have app for .pdf,Opens .pdf documents way faster than the Adobe...,NaN,NaN,NaN
28,1.0 out of 5 stars,No Longer Works :(,"Like others, I began receiving the ""invalid fi...",NaN,NaN,NaN
29,1.0 out of 5 stars,Refund my account.....,Bought for my kindle fire 10. Will not open. W...,NaN,NaN,NaN
30,5.0 out of 5 stars,Great app!,"Even though I have dyslexia, and reading is no...",NaN,NaN,NaN
31,1.0 out of 5 stars,DOES NOT WORK. SCAM! Should've listened to the...,DO NOT WASTE YOUR $4.00. APP DOESN'T EVEN OPEN...,NaN,NaN,NaN
32,2.0 out of 5 stars,Decent but not the best,I like a lot of the features. In truth I was j...,NaN,NaN,NaN
33,1.0 out of 5 stars,Don't work.,Bought and paid for and don't work on my Kindl...,NaN,NaN,NaN
34,5.0 out of 5 stars,Much better than the stock PDF reader that com...,"Most notably, it has the ability to have multi...",NaN,NaN,NaN
35,1.0 out of 5 stars,Doesn't work on Kindle Fire 10,Never opens and will not open any pdfs. Waste...,NaN,NaN,NaN
36,1.0 out of 5 stars,"Crashes repeatedly on some actions, cannot fin...",Adding strikethrough or underline to a documen...,NaN,NaN,NaN
37,1.0 out of 5 stars,Does not display PDF properly,I scanned a multiple page document at work. W...,NaN,NaN,NaN
38,2.0 out of 5 stars,"Good bones, but crashes on dropbox/email conne...",Really want to like this app. Highlighting/ann...,NaN,NaN,NaN
39,4.0 out of 5 stars,Great study app; I hope they fix the bookmark...,I really like this app for studying. I can und...,NaN,NaN,NaN
40,2.0 out of 5 stars,editing closes program,I find this little app very easy to use. Howev...,NaN,NaN,NaN
41,5.0 out of 5 stars,"Fast, full featured, amazing",This is the fastest mobile pdf reader I've eve...,NaN,NaN,NaN
42,5.0 out of 5 stars,Great for Read Aloud,I don't have time to work and read through my ...,NaN,NaN,NaN
43,3.0 out of 5 stars,Never used it,downloaded and deleted,NaN,NaN,NaN
44,1.0 out of 5 stars,Worst app I've ever bought!,It is impossible to use this app. There seems ...,NaN,NaN,NaN
45,3.0 out of 5 stars,"Good app for viewing PDF's, but hard to use",I have a Samsung Galaxy 4 and tablet. My job ...,NaN,NaN,NaN
46,1.0 out of 5 stars,"program does not work, does not load on my KIN...","DOES NOT WORK, DOES NOT LOAD ON MY KINDLE FIRE...",NaN,NaN,NaN
47,4.0 out of 5 stars,Awesome pdf editing tool,I have been testing PDF reading/editing/annota...,NaN,NaN,NaN
48,5.0 out of 5 stars,The best Android PDF reader I have found,After struggling with several Android PDF view...,NaN,NaN,NaN
49,1.0 out of 5 stars,Doesn't even open--refund please,It won't open at all. I want a refund,NaN,NaN,NaN

In [3]:
df.drop(columns=["Title_of_Review","Unnamed: 3", "Unnamed: 4", "Unnamed: 5"], inplace=True)
df.head()

                Stars                                        Base_Review
0  1.0 out of 5 stars  Don't buy this product. I purchased it for my ...
1  1.0 out of 5 stars     Get an "invalid file" error since Marshmallow.
2  1.0 out of 5 stars  I wouldn't even give it a one if I could. I wi...
3  1.0 out of 5 stars  If I could give it less stars, I would! Does n...
4  5.0 out of 5 stars  I have several apps that can open pdf files on...

In [4]:
df.dropna(inplace=True)
df.isnull().sum()

Stars          0
Base_Review    0
dtype: int64

In [5]:
df['Stars'].value_counts()

Stars
5.0 out of 5 stars    33246
1.0 out of 5 stars    21692
4.0 out of 5 stars    11603
3.0 out of 5 stars     7666
2.0 out of 5 stars     5280
a-icon-alt                1
Name: count, dtype: int64

In [6]:
df['Base_Review'] = df['Base_Review'].str.lower().str.strip()

In [7]:
noise_text = "Translate review to English"
df = df[df['Base_Review'] != noise_text]

In [8]:
df['Base_Review'] = df['Base_Review'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))

In [9]:
df = df.drop_duplicates(subset=['Base_Review', 'Stars'])

In [10]:
df = df[df['Stars'] != 'a-icon-alt'] #removes unnecessary text in the Stars column

In [11]:
df['rating'] = df['Stars'].apply(lambda x: int(float(str(x).split()[0])))
df = df.drop('Stars', axis=1)

In [12]:
X = df['Base_Review']
y = df['rating']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [14]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000, ngram_range=(1, 2)) #ignore common stop words that do not help the review. Keep the most important 5000 words
#ngrams to detect pairs of words that often appear together
X_train_tfidf = vectorizer.fit_transform(X_train)

X_test_tfidf = vectorizer.transform(X_test)

In [15]:
svm_model = LinearSVC( 
    class_weight='balanced', 
    random_state=42, 
    max_iter=2000
)

svm_model.fit(X_train_tfidf, y_train)

y_pred_svm = svm_model.predict(X_test_tfidf)

In [16]:
print(f"SVM Accuracy: {accuracy_score(y_test, y_pred_svm):.2f}")
print(classification_report(y_test, y_pred_svm))

SVM Accuracy: 0.56
              precision    recall  f1-score   support

           1       0.65      0.73      0.69      3554
           2       0.14      0.17      0.15       913
           3       0.23      0.24      0.24      1249
           4       0.37      0.30      0.33      2116
           5       0.73      0.70      0.72      5411

    accuracy                           0.56     13243
   macro avg       0.43      0.43      0.43     13243
weighted avg       0.57      0.56      0.56     13243

In [18]:
import pickle

with open("predictor.pkl", "rb") as f:
    model = pickle.load(f)

with open("tfidf.pkl", "rb") as f:
    vectorizer = pickle.load(f)